### ISSUE TITLE
Fixing the template

### ISSUE THREAD

**Issue by hongooi73** [harlecin/serverless#3]
Hi, it looks like you were having some troubles deploying the ARM template.

- I've just updated AzureRMR to fix some bugs with template deployment. Try installing the latest version from CRAN.
- If you are using the default values for all your parameters, you can set this argument to NULL in `deploy_template`: `rg$deploy_template(name=*, template="template.json", parameters=NULL)`
- The complex parameter names seem to be confusing ARM. I changed them to be just "containergroupname2" and "createcontainergroup" (to match the strings in the previous names) and then the deployment works. Well, I got an error that I don't have permission to access your sub, but that's expected.

```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "workflows_latest_name": {
            "defaultValue": "latest",
            "type": "String"
        },
        "containergroupname2": {
            "defaultValue": "/subscriptions/@{encodeURIComponent('a946be7b-3533-413d-9366-91e10c0b209b')}/resourceGroups/@{encodeURIComponent('serverless')}/providers/Microsoft.ContainerInstance/containerGroups/@{encodeURIComponent('containergroupname2')}",
            "type": "String"
        },
        "createcontainergroup": {
            "defaultValue": "/subscriptions/@{encodeURIComponent('a946be7b-3533-413d-9366-91e10c0b209b')}/resourceGroups/@{encodeURIComponent('serverless')}/providers/Microsoft.ContainerInstance/containerGroups/@{encodeURIComponent(body('Create_container_group')?['name'])}",
            "type": "String"
        },
        "connections_aci_externalid": {
            "defaultValue": "/subscriptions/a946be7b-3533-413d-9366-91e10c0b209b/resourceGroups/serverless/providers/Microsoft.Web/connections/aci",
            "type": "String"
        }
    },
...
```

I'm happy to help out on the Azure side, just let me know what needs to be done.

**Comment by harlecin** [comment]
Hey:)

sry for the late reply, was on holiday last week and had to catch up at work...

AzureRMR works perfectly:) I just made a mistake when I was trying to refactor the Azure templates + parameters json files that is what my commit was refering to. I Would like to move all infos such as subscription etc from the template json to the parameter json, but that is not the default that logic apps expects...

Thanks a lot for your offer! I will come back to you on that! I am currently quite swamped at work so it might be a while before I can find some time to work on this again unfortunately :(

**Comment by hongooi73** [comment]
No worries. I actually have a PR for one of our happy paths that is doing something very similar, and would benefit greatly from this package:

https://github.com/Azure/RBatchScoring/tree/AzureR

It shouldn't be hard to turn the underlying flow into a package.
